### ISSUE TITLE
Full tree-sitter-faust implementation available

### ISSUE THREAD

**Issue by khiner** [madskjeldgaard/tree-sitter-faust#1]
Hi @madskjeldgaard - I have implemented a full tree-sitter-faust grammar at: https://github.com/khiner/tree-sitter-faust

I plan on maintaining it, along with the nvim-treesitter language support.

Your WIP implementation really helped me get started, thanks for what you've done here!

If you end up using it, please let me know if you see any issues or have thoughts on improving.

**Comment by madskjeldgaard** [comment]
Fantastic work @khiner ! Thnks so much. I'll Archive this repo and link to yours :)
